import React from 'react';
import featureImg from '../assets/features_image.png';
import Button from './Button';

const Features = () => {
    return (
        <div className='flex flex-col items-center mt-5 m-2 p-2'>
            <h1 className='text-xl font-semibold'>Our <span className='text-[#1A8500]'>Features</span></h1>
            <div className='flex'>
                <div className='border-2 flex flex-col items-center border-[#E9E9E9] p-2 m-2'>
                    <img src={featureImg} alt="Our Features" />
                    <div className='my-2'>
                        <h1 className='font-semibold text-lg text-[#0F4901] m-2'>AI Generated Tips</h1>
                        <p className='m-2'>Receive personalized farming tips generated by AI, based on real-time weather data and historical trends, to enhance your agricultural productivity.</p>
                        <p className='m-2'>Our tips cover crop selection, planting schedules, and pest control, tailored to your specific location and weather conditions.</p>
                    </div>
                    <Button text="View More"/>
                </div>
                <div className='border-2 flex flex-col items-center border-[#E9E9E9] p-2 m-2'>
                    <img src={featureImg} alt="Our Features" />
                    <div className='my-2'>
                        <h1 className='font-semibold text-lg text-[#0F4901] m-2'>Weather Forecast</h1>
                        <p className='m-2'>Access real-time weather forecasts through our integrated weather API, helping you make informed decisions for your farming activities.</p>
                        <p className='m-2'>Receive timely weather updates and alerts to stay prepared for any changes in weather conditions.</p>
                    </div>
                    <Button text="View More"/>
                </div>
                <div className='border-2 flex flex-col items-center border-[#E9E9E9] p-2 m-2'>
                    <img src={featureImg} alt="Our Features" />
                    <div className='my-2'>
                        <h1 className='font-semibold text-lg text-[#0F4901] m-2'>Real-time Chats</h1>
                        <p className='m-2'>Communicate securely with other farmers, cooperatives, and food processing industries through our real-time messaging platform.</p>
                        <p className='m-2'>Share information, negotiate prices, and arrange logistics easily and efficiently.</p>
                    </div>
                    <Button text="View More"/>
                </div>
            </div>
        </div>
    );
}

export default Features;
